### ISSUE TITLE
Add select drop down

### ISSUE THREAD

**Issue by wipflash** [appzcoder/crud-generator#100]
This is marvelous work.

If you can add select drop down to the script it will be fully competed script.

**Comment by sohelamin** [comment]
Glad to hear that you liked it :) 
For now the enum type field is already implemented.
Will add the select type soon.

**Comment by ChangePlaces** [comment]
what will the drop down be used for?

**Comment by sohelamin** [comment]
Its nothing more than other form field type. 
People are too lazy to convert a normal text input to a select.

**Comment by sohelamin** [comment]
Hi Guys,

The select type field is supported now.
You can check from the develop version will release the stable one soon.

composer require appzcoder/crud-generator dev-develop

Docs https://github.com/appzcoder/crud-generator/tree/develop
