### ISSUE TITLE
Support index and foreign keys

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#102]
It'd be nice to append ->`index()` onto the field definition somehow! This will mean that there will probably have to be smarter parsing to the field definitions so that both of the following are valid: `foo#string#required#index` and `foo#string#index#required`

Maybe, it would help the coding if another few options were added to the crud:generate command such as `--indexes="myfield_id,myfield2_id"`? It'd have to check that the field definitions exist, but it'd keep field string parsing really simple. maybe then break the requireds into a separate option too? It would save you having to parse the fields string repetitively.

I'm envisioning something like:
`crud:generate --fields="my_field1#string,my_boss_id#integer,my_name#string" --requireds="my_boss_id, my_name" --indexes="my_boss_id,my_name" foreigns="my_boss_id#id#bosses" --pk=id`

where `foreign` will translate to `$table->foreign('my_boss_id')->references('id')->on('bosses')`?

This idea would fit nicely into your "stub"s design!

Composite indexes could then be defined by using a hash,  `--index="some_field,fld1#fld2"`

**Comment by sohelamin** [comment]
Hi @ChangePlaces 

I liked your proposal.
We can add --indexes & --foreigns as you suggested.

But for --required option how will you handle the validation rules ? 
eg: ```--fields="body#text#required_with:title|alpha_num"```
