### ISSUE TITLE
trim field names

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#103]
when creating field names, trim the excess space from the start and end of the field name, e.g. `--fields="foo#string, bar#integer, zar#boolean"` results in field names of "foo", "&nbsp;bar" and " zar" inside the html.

UPDATE: this is odd as I've checked through the code, and you are trim'ming where necessary. Maybe it's the templating, I'll check further.

**Comment by sohelamin** [comment]
Okay

**Comment by ChangePlaces** [comment]
Please, leave this open to remind me to have a look at why it's happening in the template! It's bizarre

**Comment by sohelamin** [comment]
No I didn't implement yet. 
You can proceed and many many thanks for your effort :)
