### ISSUE TITLE
More control over namespaces for model

### ISSUE THREAD

**Issue by pbehrens** [appzcoder/crud-generator#107]
It'd be awesome if you could specify a namespace for the model being generated. So far I've only been able to get them generated at App\SomeModel.php. A flag like --model-namespace=Models/Front/Blog that creates the model in that location.  Otherwise, you need to move the model then edit its' templates and the controller to reference the new namespace.

**Comment by ChangePlaces** [comment]
+1 this

there is a namespace argument  - forget the actual option - but it seems to only put the controller in a namespace, not the model

**Comment by ChangePlaces** [comment]
if no one's going to tackle this, i could add it to my todo list after I sort the pr out?

**Comment by ChangePlaces** [comment]
well, it's kinda already possible by doing: `./artisan crud:generate "MyNamespace\MyModelName" --fields="..."`

This messes up a lot of things though, so I'm going to sort through that

**Comment by ChangePlaces** [comment]
OK, done the following changes: 

- "namespace" argument is renamed to `controller-namespace`
- added `model-namespace` argument to crud:generate

**Comment by pbehrens** [comment]
@ChangePlaces Awesome! This is great

**Comment by ChangePlaces** [comment]
if confirmed and all happy, then can this be closed?
