### ISSUE TITLE
support composite indexes

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#109]
more of a note to myself, which I'll implement soon:
e.g.:

--pk="field1|field2" primary key on field1 and field2
--indexes="field1|field2,field3" composite index on field1 and field2, and another separate index on field3

**Comment by sohelamin** [comment]
Okay that can be implemented

**Comment by ChangePlaces** [comment]
has this been implemented?

**Comment by sohelamin** [comment]
Nope, You can do that.

**Comment by ChangePlaces** [comment]
gee, thanks! don't close this issue then!

**Comment by ChangePlaces** [comment]
this is getting bloody confusing. don't close issues that aren't resolved.

**Comment by ChangePlaces** [comment]
#114 sorted this
