### ISSUE TITLE
don't hardcode model namespace in get_enum_values

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#111]
$model_class = "App\\$model";

this will be wrong as model-namespace can be altered

**Comment by sohelamin** [comment]
This was a temporary fix.

**Comment by ChangePlaces** [comment]
yeah, i haven't looked at it, but enum handling seems hackish! I don't really know how it could be used sensibly, so I've avoided it. I'll have a look at it sometime.
