### ISSUE TITLE
Create a form validation class instead of using the validatesRequest trait of the controller?

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#113]
If a separate class was generated for form validation, it would allow the user to modify the validation as necessary

**Comment by sohelamin** [comment]
Okay that can be implemented.

**Comment by sohelamin** [comment]
But we can control it through config file.
If user still don't want to use validation class then it will just use the trait.
https://github.com/appzcoder/crud-generator/blob/1.1/config/crudgenerator.php

**Comment by ChangePlaces** [comment]
i think maybe it should be an optional extra as for 80% of the cases, the trait will be good enough. so maybe something like `--create-validation-class=yes` to specify its creation

**Comment by sohelamin** [comment]
We can use config file.

**Comment by ChangePlaces** [comment]
i've never used the config file. the problem with a config file is that it's difficult to define whether to create a class or not on a per class basis

**Comment by sohelamin** [comment]
Right, But I don't prefer to put too many arguments on the command line.
So if we have minor config then we can use the config file otherwise we can use the commands.
