### ISSUE TITLE
create unit test stub

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#115]
even an empty unit test class would be useful to start manually populating tests with

**Comment by sohelamin** [comment]
Stub for what? I have a plan to implement unit testing on this package.

**Comment by ChangePlaces** [comment]
what's your plan?

**Comment by sohelamin** [comment]
Unit testing same as the other package do. 
Whats actually you meant by the stub? stub actually template file for user to auto creation or generation.

**Comment by ChangePlaces** [comment]
i think it's pointless creating unit tests that just test the crud functionality (like I've seen another that does) because that's testing a feature of laravel rather than the user's code. I'm initially thinking of creating something that tests validation rules initially because code changes can easily break validation rules!

**Comment by sohelamin** [comment]
Okay but we can implement it later.
Thanks for the idea.

**Comment by ChangePlaces** [comment]
yeah, i agree not a high priority, but i may take a stab at it whilst i've got my head in this. i'm looking at a huge text file with about 50 crud entities defined so would like to get this code in the best place i possibly can!
