### ISSUE TITLE
create sample database seeder for model?

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#117]
faker could be used to populate fields depending on field type and a sample database seeder created in database/seeders

**Comment by sohelamin** [comment]
Not necessary now.

**Comment by ChangePlaces** [comment]
why isn't it necessary?

**Comment by sohelamin** [comment]
Because, nobody request it yet.
If you got time then you can proceed.

**Comment by ChangePlaces** [comment]
well that's why i created the issue in the first place as a reminder for me to do it!
