### ISSUE TITLE
Use semicolons as separators instead of comma

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#120]
due to #119 i think instead of commas being used, semicolons should be used instead:

e.g. from `--fields"title#string,body#text"` to `--fields"title#string;body#text"`

this is because in some args, comma is a valid character

**Comment by sohelamin** [comment]
Can you explain a bit more where actually are you having issues?

If it's not a big issue then I don't think it'll wise idea to change it cause, through changing existing users will get confused.

**Comment by sohelamin** [comment]
Duplicate issue #119

**Comment by ChangePlaces** [comment]
this was actually an issue in the previous version because in form validation, required_with uses commas to separate fields that are required but commas are already used to separate additional validation rules, so a delimiter other than comma has to be used
