### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by marwan2** [appzcoder/crud-generator#122]
What about adding a type for creating input[type="file"] and so implement a simple upload file on the Controller:

`
```
        if($request->hasFile('image'))
        {
            $upload_path = public_path('/uploads/');
            $name = $request->file('image')->getClientOriginalExtension();
            $request->file('image')->move($upload_path, $name);
            $news->image = str_slug($name);
            $news->save();
        }
```
`

**Comment by sohelamin** [comment]
I'll add this on next update.

**Comment by sohelamin** [comment]
Hi @marwan2 

Can you find time to check the file upload?

It is implemented on develop branch
composer require appzcoder/crud-generator dev-develop

Docs https://github.com/appzcoder/crud-generator/tree/develop
