### ISSUE TITLE
Suggestion: widget generation

### ISSUE THREAD

**Issue by eduardoarandah** [appzcoder/crud-generator#124]
Suggestion: 

**new command:  widgets**

    php artisan crud:widgets

So if I widget a "customer" model, I get:

**A dropdown**

    {!! Form::select('customer', Customer::->lists('name', 'id')->all(), $customer, ['class' => 'form-control']) !!}

**A detail-widget, to be called from inside other views**

example: when showing an invoice, I want a customer detail-widget on the right

**A list widget, to be called based on foreign key**

example: when showing a customer type , I want a customer-list-widget on the right, based on its type_id foreign key

what do you think?

**Comment by sohelamin** [comment]
Hi @eduardoarandah 

Your idea is not bad but I don't want to add this widget feature now cause I want to make it simpler crud generator only.
