### ISSUE TITLE
Undefinded variable: loop

### ISSUE THREAD

**Issue by mojoblanco** [appzcoder/crud-generator#129]
I get this error when i visit the index page

> Undefined variable: loop (View: /home/ubuntu/workspace/app/resources/views/admin/posts/index.blade.php)

**Comment by sohelamin** [comment]
I guess you're using older version of laravel.
Please change 
```
@foreach($crudName as $item)
    <tr>
        <td>{{ $loop->iteration }}</td>
```
to
```
{{-- */$x=0;/* --}}
@foreach($crudName as $item)
    {{-- */$x++;/* --}}
    <tr>
        <td>{{ $x }}</td>
```

I'll fix it soon in another way.

**Comment by mojoblanco** [comment]
Okay, Thanks. I am using Laravel 5.2.
