### ISSUE TITLE
Unable to make validation 

### ISSUE THREAD

**Issue by vigneshmunisamy** [appzcoder/crud-generator#130]
Thanks for share code curd generator. But am facing some issue. While adding a validation for the field
am getting 
COmmand 

php artisan crud:view blog_test --fields="title#required|max:255; body#text" --view-path="directory" --route-group=admin

Exception 
" [ErrorException]                   
  Undefined index: required|max:255  "
![screenshot from 2016-09-23 10 12 14](https://cloud.githubusercontent.com/assets/8588070/18774392/3d04258c-8176-11e6-8fb3-d330946d98a8.png)

and one more doubt i want create a select box.whatever you did fine.that is statically ,but i want make it as a dynamic .

  
  category#select#options=technology,tips,health;
...In this Category value need to get from db.

IF you give some more brief document ,it's too much helpful foe me and other also...

thanks   so much

**Comment by sohelamin** [comment]
Hi @vigneshmunisamy Please check the documents carefully.

Your command is not correct it will be
```
php artisan crud:view blog_test --fields="title#string; body#text" --validations="title#required|max:255" --view-path="directory" --route-group=admin
```
instead of yours
```
php artisan crud:view blog_test --fields="title#required|max:255; body#text" --view-path="directory" --route-group=admin
```

And for the select box you need to change the code yourself. It just a way to add select box only.
