### ISSUE TITLE
Where did all the changes I made vanish to?

### ISSUE THREAD

**Issue by ChangePlaces** [appzcoder/crud-generator#131]
I practically rewrote this is many large places as it was a total mess, and yet the contributions show that I contributed 2 lines. Did you copy/paste my code so you'd get the credit for it? I know for sure they're in the codebase.

**Comment by sohelamin** [comment]
@ChangePlaces check the commit you will find your name there.
You didn't git config to your local machine that's why your username not showing properly.
I always respect my contributors.

**Comment by sohelamin** [comment]
@ChangePlaces Did you get it?
