### ISSUE TITLE
editing a record table: date field is not displayed correctly in the view

### ISSUE THREAD

**Issue by fmarkos** [appzcoder/crud-generator#137]
editing a record table: date field is not displayed correctly in the view,
it comes up empty (there is data in the database created with the auto generated create view)
using Laravel 5.3

**Comment by johnnydoe82** [comment]
At least for strings it seems to work for me perfectly. What kind of data field is it, where this problem occurs in your app?

**Comment by fmarkos** [comment]
Fixed it by changing in my project this line: 
{!! Form::input('datetime-local', 'start', null, ['class' => 'form-control']) !!}
to this:
{!! Form::input('datetime-local', 'start', $project->start->format('Y-m-d\TH:i'), ['class' => 'form-control']) !!}

This is in the common form.blade.php
