### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JamesTimms** [appzcoder/crud-generator#138]
Hi there,

Just wanted to confirm that the license for this project is MIT? There is no mention on the README file but it say "license": "MIT" in your composer file.

Thanks,
James

**Comment by sohelamin** [comment]
Yes the license is MIT.
You will find a licence badge on the top of the readme file also.
<img width="484" alt="screen shot 2016-12-05 at 9 29 25 pm" src="https://cloud.githubusercontent.com/assets/1708683/20890730/2417f2ba-bb32-11e6-8fd2-485729d9e273.png">

**Comment by JamesTimms** [comment]
Ah sorry I missed that, was looking for the License section at the bottom of the file. Thanks for getting back to me :)
