### ISSUE TITLE
Crud fields from json file

### ISSUE THREAD

**Issue by sohelamin** [appzcoder/crud-generator#139]
```php artisan crud:generate Posts --fields_from_file="/path/to/fields.json" --view-path=admin --controller-namespace=Admin --route-group=admin```

```json
{
   "fields": [
        {
            "name": "title",
            "type": "string"        
        },
        {
            "name": "content",
            "type": "text"
        },
        {
            "name": "category",
            "type": "select",
            "options": ["technology", "tips", "health"]
        }
   ] 
}
```

**Comment by dimasip** [comment]
any chance to make crud fields from existing migration tables?

**Comment by sohelamin** [comment]
No plan yet but thanks for your idea I'll consider it in future update.

**Comment by sohelamin** [comment]
I've made a commit at ed539c1
You can check via ```composer require appzcoder/crud-generator:dev-master```
