### ISSUE TITLE
crudupdate

### ISSUE THREAD

**Issue by butoibogdan** [appzcoder/crud-generator#14]

**Comment by appzcoder** [comment]
Hello @butoibogdan 

What do you mean by this blank issue?
I'm going to close this.

**Comment by butoibogdan** [comment]
Hello
Sorry for this issue. 
I'm rely new in git hub and I create an issue from a mistake
I need to make on your crud generator some personal customization and I didn't won't to disturb you with a pull request. Really I didn't know what is the best solution offer by git hub clone or fork. 
Thanks a lot
Pe 13.06.2015 18:24, appzcoder <notifications@github.com> a scris:Hello @butoibogdan 

What do you mean by this blank issue?
I'm going to close this.
