### ISSUE TITLE
Change View for generated view 

### ISSUE THREAD

**Issue by pc-mon** [appzcoder/crud-generator#141]
hello
thank you for amazing work 
I have little problem to modify generated view
and thank you

**Comment by pc-mon** [comment]
I just didn't find this view 
return view('admin.costs.cost.show', compact('cost'));

**Comment by sohelamin** [comment]
@pc-mon Can you share which command did you run?

**Comment by pc-mon** [comment]
my code : git clone https://pc-moon@bitbucket.org/pc-moon/laravel-train-system.git

**Comment by pc-mon** [comment]
i follow how to install it normal
