### ISSUE TITLE
custom method not callable

### ISSUE THREAD

**Issue by balvirsingh** [appzcoder/crud-generator#142]
Hi,

version: laravel 5.3

I generated crud through crud generator, works fine. Now I add one new method in same controller but I unable to call that function. How can I set route for that added method in controller.

I also confused that where managed routes for crud which generated automatically like edit, create etc.
In routes/web.php file there is only one line mentioned. 
Route::resource('user', 'UserController');

how this line managed all the routes of method.
Please explain.

**Comment by sohelamin** [comment]
@balvirsingh Your issue isn't relevant with this package.
You can add any method and the route as well.
eg.
```php
Route::get('user/custom-route', 'UserController@customMethod')
```

**Comment by johnnydoe82** [comment]
@balvirsingh Probably it is useful to know the following passage from the docs, which I overlooked for a long time too:
[https://laravel.com/docs/5.3/controllers#resource-controllers](https://laravel.com/docs/5.3/controllers#resource-controllers)  ;)
