### ISSUE TITLE
Add config for DB connection setting

### ISSUE THREAD

**Issue by randycasburn** [appzcoder/crud-generator#143]
Common Usecase: 

users DB for user, password-resets, permissions, roles etc
api DB for application data

Easy as 
1. adding a config setting for
   a.  user_db_connection with env default 
   b. data_db_connection with env default 
2. adding the $connection property to each model stub and the migration stub:
`    protected $connection = 'users';
`
3. The tricky part is modifying the User Model, but since you are simply using the default Laravel model you 'could' stub that out too.

**Comment by bramburn** [comment]
I'm confused, how is that part of a CRUD?

**Comment by randycasburn** [comment]
`(morphing into mean human...)`

New to Laravel bramburn? It's OK...I get it.
(https://laravel.com/docs/5.3/database#using-multiple-database-connections) 

Hmmmm....are you sure you are not confused about the difference between CRUD and code generation? 

`(returning to trying to be a nice human)`

I'm sorry the provided use case description didn't answer your question, please allow me to try in a different way:

The ability to control a DB connection setting as [described in the docs](https://laravel.com/docs/5.3/database#using-multiple-database-connections),  would allow one to CRUD to/from [multiple databases](https://laravel.com/docs/5.3/database#using-multiple-database-connections) within the same application. A common use case.

could Create a user row in **DB A** (maybe called **users**)
could Read a product row from **DB B** (maybe called **api**)
could Update an order row in **DB B** (**api** again)
could Delete a row from the **rude_question** table in the **comment DB**

**Comment by bramburn** [comment]
ok I get it, I was really confused as to what you meant.

I see the usecase that you are looking for. I am currently developing a complex CRUD generator, maybe it could be something that can be added to the **complexity** and assign DB connection to create, read, update, and delete.

Something like this:?

```
{
    "CRUD": [{
        "name": "TestPost",
        "route": "yes",
        "routePath": "testtt",
        "routeGroup": "",
        "perPage": "",
        "controller_namespace": "Test\\",
        "modelName": "",
        "modelNamespace": "",
        "validations": "",
        **"DBConnection": {
            "create": "createDB",
            "read": "readDB",
            "update": "updateDB",
            "delete": "deleteDB"
        },**
        "data": {
            "fields": [{
                "name": "title",
                "type": "string",
                "showform": "yes"
            }, {
                "name": "content",
                "type": "text",
                "showform": "yes"
            }, {
                "name": "attachment",
                "route": "yes",
                "type": "OneToMany",
                "addFormToParent": "yes",
                "database_name": "attachments",
                "data": {
                    "name": "attachments",
                    "route": "yes",
                    "routePath": "",
                    "routeGroup": "",
                    "perPage": "",
                    "controller_namespace": "Test\\Attachments\\",
                    "modelName": "post_attachments",
                    "modelNamespace": "",
                    "fields": [{
                        "name": "title",
                        "type": "string",
                        "showform": "yes"
                    }, {
                        "name": "file",
                        "type": "file",
                        "showform": "yes"
                    }]
                }
            }, {
                "name": "view",
                "type": "integer",
                "showform": "no"
            }, {
                "name": "comments",
                "type": "OneToMany",
                "addFormToParent": "yes",
                "database_name": "testComments",
                "data": {
                    "name": "comments",
                    "route": "yes",
                    "routePath": "",
                    "routeGroup": "",
                    "perPage": "",
                    "controller_namespace": "Test\\Comments\\",
                    "modelName": "post_attachments",
                    "modelNamespace": "",
                    "fields": [{
                        "name": "comment",
                        "type": "text",
                        "showform": "yes"
                    }]
                }
            }]
        }
    }]
}
```

**Comment by sohelamin** [comment]
@randycasburn The DB configuration is totally up to the application. 
The package will handle that.
