### ISSUE TITLE
crud generator with 1-n relations

### ISSUE THREAD

**Issue by wrazouk** [appzcoder/crud-generator#147]
Hi,
First, many thanks for your effort.
My problem is that:
How to use crud generator with foreign key relations?
Example: I have `countries` table with `id, name` fields and `cities` table with `id, name, country_id` fields. Now when I want to add a new city, what are the fields shall I put in my `php artisan` command? and how to display a dropdown menu containing all the countries in the database?
I tried to use `--foreign-keys="country_id#id#countries#cascade"`, it worked with the migration file, but didn't work in the view
Thanks in advance :)

**Comment by asilverstein** [comment]
+1

**Comment by sohelamin** [comment]
@wrazouk You need to do it yourself at now. We've no plan yet for this :)

**Comment by kemal-atila** [comment]
+2
