### ISSUE TITLE
 There are no commands defined in the "crud" namespace.

### ISSUE THREAD

**Issue by polarix2017** [appzcoder/crud-generator#148]
All the installation steps are correctly done. 
The command i try to execute is:

`php artisan crud:controller BoxController --crud-name=boxes --model-name=Box --view-path="boxes" --route=no`
The error:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "crud" namespace.
```

Just updated to Laravel Framework 5.4.12

**Comment by polarix2017** [comment]
The command:
` php artisan config:clear`
fix it.

**Comment by markwalet** [comment]
Please close this issue.

**Comment by sh6210** [comment]
for me, php artisan config:clear didn't solve the problem.
Still getting the error.
