### ISSUE TITLE
Problem with assign a custom path after any submit procedure

### ISSUE THREAD

**Issue by imohd23** [appzcoder/crud-generator#154]
I have a problem with redirecting the form after it has been submitted. I have in my link `\en\admin\something` I tried to change it in different locations and I couldn't figure out where to change and what to change. Also, how can I modify the creation process with this code to a specific route for redirecting the page and after submitting the forms. code `php artisan crud:generate Posts --fields="title#string; content#text; category#select#options=technology,tips,health" --view-path=admin --controller-namespace=Admin --route-group=admin`

Many thanks friend for your tool but it needs more documentations and will be super useful

**Comment by sohelamin** [comment]
@imohd23 You could update the redirect url from the `PostController`.
You need to do it yourself there is nothing to do the tool
