### ISSUE TITLE
localize and locales not working

### ISSUE THREAD

**Issue by midrees** [appzcoder/crud-generator#158]
I am facing one problem, if you can suggest some solution. As mentioned on the home page, under Options sections, there are 2 options for localize and locales. I have used it but I did not see its working. May be I did something wrong. Can you please suggest how to make it work. I am using two languages english(ltr) and arabic(rtl).

**Comment by fomvasss** [comment]
I also had the same problem.
You need to rename the created localization files in the localization folders: make the first letter small
For example: **/resources/lang/en/Post.php** change to **/resources/lang/en/post.php**

**Comment by midrees** [comment]
Thanks for your suggestion fomvass. I appreciate your feedback. Yes I did this change you mentioned. Can you please suggest how can I access one view for two different locales, how the user will get access to one specific locale, may be it will have different urls, if so, how these urls will be designed, either by myself of this appzcoder generator will do it by some way. Can you please elaborate a bit more detail about how to use it. I

**Comment by fomvasss** [comment]
Manually fill the array: /resources/lang/en/post.php
```
return [
     'title' => 'Your Title Name',
// ...
];
```
To enable the desired language, use: App::setLocale($locale) or app()->setLocale($locale)
In Blade, use {{trans('post.title')}} for the required fields
For language switching I sometimes use the plugin https://github.com/mcamara/laravel-localization
Read https://laravel.com/docs/5.4/localization#introduction

**Comment by midrees** [comment]
Thanks fomvass, for sharing this useful information. I don't know if I am already using a plugin "appzcoder/crud-generator" and if I add-up another plugin, may it cause any problematic behavior? Since I am new to Laravel and don't know much about this.

**Comment by fomvasss** [comment]
These are completely different plugins. Of course, they can be used together. Compatibility 100%

**Comment by midrees** [comment]
Thanks fomvass. I will try this plugin.
