### ISSUE TITLE
Crud issue 

### ISSUE THREAD

**Issue by cent040** [appzcoder/crud-generator#159]
[Symfony\Component\Console\Exception\CommandNotFoundException] 
  There are no commands defined in the "crud" namespace.

**Comment by sohelamin** [comment]
@cent040 You might not be followed the setup instructions carefully.

**Comment by cent040** [comment]
I followed all instruction. I am using 5.4. is it ok with **Laravel5.4**. 
Error is about namespace crud. we only publish provider in **config/app.php**. is we need to add alias as well or not.

**Comment by sohelamin** [comment]
No need to use any aliases.
Just follow this tutorial https://www.youtube.com/watch?v=831-PFBsYfw and let me know if you're still having any issues.
