### ISSUE TITLE
Requirement

### ISSUE THREAD

**Issue by butoibogdan** [appzcoder/crud-generator#16]
Please, how can i link the path from view stub with my private views. Can i use a config files to define the target of views. I want to use in composer json the original appzcoder but i don't wont to modified my views after update.
Thank you very much

**Comment by sohelamin** [comment]
Hello @butoibogdan,
Do you mean to change the location to your custom location for generating the view files?
You can do it through changing the target directory from here https://github.com/appzcoder/crud-generator/blob/master/src/CrudViewCommand.php
Please let me know if you seeking another things.
Thanks
