### ISSUE TITLE
Decoupling Html/Form Helper Package

### ISSUE THREAD

**Issue by sohelamin** [appzcoder/crud-generator#160]
I've a plan to decouple or have an option to use the Html/Form Helper or not.

**Comment by sohelamin** [comment]
Hi Guys, I'm planning to get rid the Html/Form helper totally.
Do you think it will help you? or should I have an option for Html/Form helper as well?

**Comment by mojoblanco** [comment]
Don't get rid of the helper totally, It makes scaffolding easier. Having an option for it would be better. I personally would still want to use the helper

**Comment by sohelamin** [comment]
Yeah, I have plan for that even more flexible customization. User can use any helper package their own now. I'm working on it :) check the develop branch

**Comment by johnnydoe82** [comment]
In my opinion the Html/Form Helper could be removed completely, but if some other users want to keep it, it's surely better to have an option for it ;)

Will it also be possible to exclude Twitter Bootstrap code by an option in the new version you are developing?

I used to use some custom stubs each time when I installed the crud-generator to get rid of the Html/Form Helper and Twitter Bootstrap code: https://github.com/johnnydoe82/appzcoder-crud-generator-stubs 
But in newer versions my version doesn not work completely anymore and there are some really "dirty" hacks I did in lack of better knwoledge of package programming on my behalf... 
But maybe there are some areas where I can help somehow with the new version? Please let me know :)

**Comment by sohelamin** [comment]
@johnnydoe82 I've no plan to decouple the bootstrap codes yet, but if you can help in anyway then you're always welcome :)

**Comment by sohelamin** [comment]
Implemented
