### ISSUE TITLE
Labels of options in select field 

### ISSUE THREAD

**Issue by mithublue** [appzcoder/crud-generator#164]
It could be much better if the options field would be in the format

array(
'opt1' => 'Opt 1',
'opt2' => 'Opt 2'
)

instead of 
array( 'opt1', 'opt2')

Reason : If the developer shuffles the array elements in later time, it may show the wrong option selected in the posts created already

**Comment by sohelamin** [comment]
@mithublue You can make a PR into develop branch.

**Comment by sohelamin** [comment]
Implemented
