### ISSUE TITLE
Thoughts on adding a rich text editor? [Enhancement]

### ISSUE THREAD

**Issue by georgewritescode** [appzcoder/crud-generator#166]
I think that adding a rich text editor for text fields like this:
https://github.com/quilljs/quill

Would be beneficial. What do you think?

**Comment by sohelamin** [comment]
@georgewritescode Adding rich text editor could be a good idea. But didn't want to bind users to use a specific one cause, everyone has different preferences.

**Comment by georgewritescode** [comment]
@sohelamin  I agree but just having one in the backend I don't think would be a bad thing as it would make editing text fields easier. Including CK editor wouldnt mean the application cannot use other editors elsewhere in the app. We could even include it via CDN. What do you think?
