### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by 24tech** [appzcoder/crud-generator#173]
Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()

**Comment by sohelamin** [comment]
@24tech Did you followed all instructions correctly.
And let me know your laravel version to reproduce the issue.

**Comment by GabrielDvt** [comment]
Hi. I'm having the same issue.

Yes, I followed all the instructions correctly and my laravel version is 5.4.

**Comment by shakeelcse09** [comment]
Fatal error: Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()

in CrudControllerCommand.php line 76
at CrudControllerCommand->alreadyExists('admin\ExpenseController') in GeneratorCommand.php line 56
at GeneratorCommand->fire()

i am using laravel admin and version 5.2.* and having the same problem here

**Comment by sohelamin** [comment]
Hi Guys,

I couldn't reproduce the issue. I just tested with Laravel v5.4.23
Please update and check again or let me know your version & command

**Comment by cukulkarni** [comment]
![crudgenerator error](https://cloud.githubusercontent.com/assets/28684235/26058687/845e0bbc-399c-11e7-8ce6-da24e6e9d34b.png)


[37;41m                                                                                                   [39;49m
[37;41m  [Symfony\Component\Debug\Exception\FatalThrowableError]                                          [39;49m
[37;41m  Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()  [39;49m
[37;41m

**Comment by cukulkarni** [comment]
I just digged into it.. If you look at  it:

CrudControllerCommand looks if a class exists or not using AlreadyExists method of it and inside it calls QualifyClass.

Now, QualifyClass should be there somewhere in ::
A. CrudControllerCommand
B. GeneratorCommand
C. Command
D. SymfonyCommand
E. Command -- In console -- this is base command
However, qualifyClass method does not exist in any of these classes.
Apparently, people who are facing this have upgraded Laravel framework from older to 5.2

**Comment by shakeelcse09** [comment]
its ok with 5.4.* i have tested but not in the 5.2.* :(

**Comment by eullercdr** [comment]
Not worked in 5.1 :(

**Comment by berbagimadani** [comment]
Not worked in 5.2 
"Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()"
:(

**Comment by pradeep-rajapaksha** [comment]
I just changed a line of code in `vendor\appzcoder\CrudGenerator\Commands\CrudControllerCommand.php` line #76, to `return $this->files->exists($this->getPath($rawName));` 
replacing `return $this->files->exists($this->getPath($this->qualifyClass($rawName)));` and its worked! 

It may not the solution but, at the moment, that's what I did. 
Hey @Appzcoder dev, I think you missed that qualifyClass() in somewhere. 
Please update it. 

Cheers!

**Comment by okaufmann** [comment]
I have the same error using Laravel 5.3.31.

**Comment by sohelamin** [comment]
Sorry guys, I could no manage time to fix the issue.
Just fixed it now at the new release 2.0.5 please check and let me know if you having any issues.
