### ISSUE TITLE
show page wrong

### ISSUE THREAD

**Issue by skytree8** [appzcoder/crud-generator#174]
when i make curd,show page is wrong：
Parse error: syntax error, unexpected '%', expecting variable (T_VARIABLE) or '{' or '$' (View: .../post2s/show.blade.php)

why is this,thank you.

**Comment by ayolana** [comment]
Same Error here.

**Comment by sohelamin** [comment]
Please use this config file https://github.com/appzcoder/crud-generator/blob/master/config/crudgenerator.php
And let me know if you're having the issue again.

**Comment by skytree8** [comment]
cool,there is no Error,Thanks very much.
