### ISSUE TITLE
Error in crud generator

### ISSUE THREAD

**Issue by vitormicillo** [appzcoder/crud-generator#178]
hi,
I am trying to run the crud generator on a .json files that I created, but it is returning me this error:

php artisan crud:generate Imoveis --fields_from_file="tests/json_crud/imoveis.json" --view-path=admin --controller-namespace=Admin --route-group=admin

[ErrorException]                      
Trying to get property of non-object

**Comment by georgewritescode** [comment]
check that your json is valid
