### ISSUE TITLE
Is there any way use this project on lumen?

### ISSUE THREAD

**Issue by gangstar902** [appzcoder/crud-generator#182]
lumen is not laravel, so it lacks a lot feature like artisan command publish, config ... etc. But this project seems depend on this. Is there any way use this project on lumen?

**Comment by sohelamin** [comment]
No this package isn't supported in Lumen

**Comment by acoard** [comment]
[According to this post you made on Laracasts](https://laracasts.com/discuss/channels/lumen/crud-with-lumen/replies/74863), this supports Lumen.  Is that post incorrect?

This looked right up my alley, I just need a few simple crud/admin pages for a lumen project.
