### ISSUE TITLE
whene i try to generate Crud a < ' > added to first field on migration

### ISSUE THREAD

**Issue by Oxy123** [appzcoder/crud-generator#189]
`public function up()
{
Schema::create('posts', function(Blueprint $table) {
$table->increments('id');
$table->string('' title'); ## // you can see automaticly add a '
$table->text('content');
$table->string('category');
$table->timestamps();
});`
i tape in my console 

` public function up()
    {
        Schema::create('posts', function(Blueprint $table) {
            $table->increments('id');
            $table->string('' title');
            $table->text('content');
            $table->string('category');
            $table->timestamps();
        });`

**Comment by sohelamin** [comment]
Please share your command which you ran & code is ugly to see.

**Comment by Oxy123** [comment]
i use the example  command 

`php artisan crud:generate Posts --fields='title#string; content#text; category#select#options={"technology": "Technology", "tips": "Tips", "health": "Health"}' --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=html
`

**migration generated :** 

`class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function(Blueprint $table) {
            $table->increments('id');
            $table->string(''title');
            $table->text('content');
            $table->string('category');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('posts');
    }
}
`

**Cotntroller generated ( index action ) :** 

`public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $psosts = Psost::where('"title', 'LIKE', "%$keyword%")
				->orWhere('content', 'LIKE', "%$keyword%")
				->orWhere('category', 'LIKE', "%$keyword%")
				->paginate($perPage);
        } else {
            $psosts = Psost::paginate($perPage);
        }

        return view('psosts.index', compact('psosts'));
    }`

**form.blade.html :**

`<div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
    <label for="' title" class="col-md-4 control-label">{{ '' Title' }}</label>
    <div class="col-md-6">
        <input class="form-control" name="' title" type="text" id="' title" value="{{ $post->title or ''}}" >
        {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('content') ? 'has-error' : ''}}">
    <label for="content" class="col-md-4 control-label">{{ 'Content' }}</label>
    <div class="col-md-6">
        <textarea class="form-control" rows="5" name="content" type="textarea" id="content" >{{ $post->content or ''}}</textarea>
        {!! $errors->first('content', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('category') ? 'has-error' : ''}}">
    <label for="category" class="col-md-4 control-label">{{ 'Category' }}</label>
    <div class="col-md-6">
        <select name="category" class="form-control" id="category" >
    @foreach (json_decode('{"technology": "Technology", "tips": "Tips", "health": "Health"}', true) as $optionKey => $optionValue)
        <option value="{{ $optionKey }}" {{ (isset($post->category) && $post->category == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
    @endforeach
</select>
        {!! $errors->first('category', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-4 col-md-4">
        <input class="btn btn-primary" type="submit" value="{{ $submitButtonText or 'Create' }}">
    </div>
</div>
`

**Comment by Oxy123** [comment]
there is a single quote add before first fieled ( title in this example )

**Comment by sohelamin** [comment]
Could not reproduce this issue
