### ISSUE TITLE
File Could not be downloaded while installing the package

### ISSUE THREAD

**Issue by ashokbasnet** [appzcoder/crud-generator#19]
When I ran command:- composer require appzcoder/crud-generator

I got following error.

The "http://packagist.org/p/provider-2013%248fdf62067f4932e57f307bef5e48580c504f74fa044a7ddac59e496d065deb5e.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

Please let me know.

**Comment by sohelamin** [comment]
Hi @ashokbasnet 
Have tried again?
Its seems working. There was might be an issue with packagist server

**Comment by ashokbasnet** [comment]
Hello @sohelamin , 
Thanks for the reply. It was due to the fact that packagist server was bit slower here.

Will explorer the features. 

Thanks
