### ISSUE TITLE
"search and replace" ?

### ISSUE THREAD

**Issue by GMaxera** [appzcoder/crud-generator#195]
Is it possible to do a "search and replace" in order to amend multiple rows in one go ?

**Comment by sohelamin** [comment]
I did not get you, can you please explain with an example?

**Comment by GMaxera** [comment]
I saw your video and your tool is able to display all the row into a Model.
There are buttons for "delete", "edit" ... 
wondering if there is an option to have something like "search and replace" into a columns.

Something like this tools: https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

**Comment by GMaxera** [comment]
So, supposing there is a column called "content" ... and there are 543 rows on which "content" contains a typo ... like "wiht" ... I'd like to have somethings where I can specify to search for "wiht" and replace it with "with".

**Comment by sohelamin** [comment]
No I've no plan for this now :)
