### ISSUE TITLE
getting textarea instead of text in form view

### ISSUE THREAD

**Issue by rajeshchapagain** [appzcoder/crud-generator#196]
while using  `php artisan crud:view posts --fields="name#text"` I am getting textarea as input field instead of text. Why is this happening?? I am referring this link in documentation [https://github.com/appzcoder/crud-generator/blob/master/doc/fields.md](url)

**Comment by sohelamin** [comment]
Use `string` instead.
Docs need to be updated.

**Comment by rajeshchapagain** [comment]
@sohelamin Thanks. It worked!!!
