### ISSUE TITLE
Stub assumptions

### ISSUE THREAD

**Issue by lplume** [appzcoder/crud-generator#20]
I found out that the stub assumes the primary key column is "id", and that the model is "timestampable". As a first time laravel user, im not sure, but is there a way to override the stub?

thanks you for the great work!

**Comment by sohelamin** [comment]
Hi @lplume,

It is the default or best practise to make id collumn as primary key and use the time stamp on laravel as well. If you needed you can modify the stub in your local file or you can modify the migration after generating the migration.

Please feel free to ask me if any other assistance required.

Thanks
Sohel Amin

**Comment by lplume** [comment]
Hi there, thanks for pointing this out. I do not completely agree that the primary key should be named "id". Unfortunately eloquent pk cannot be composite, relying on naming the pk "id" is often usless, since there are often better expressive pk name column (think of business vat code). Anyway it's fine for most of the small/medium projects. Please consider this as a personal preference :).
About the stub, it is located in the vendor directory, the vendor should never be modified, unless a pull request/fork (what if your repo is updated and I run a composer update?); this crud is pretty awesome, if you could make the stub ovveridable would be great! Mind I wrote you as I do not know laravel that much and cannot think of a way to do it.

Again thanks for the effort and this great crud generator!

**Comment by sohelamin** [comment]
Hi @radiart,

I've added some new features recently.
You can set your primary key as bellow command:
php artisan crud:generate Person --fields="name:string, email:string, phone:integer, message:text" --pk=id

This feature you will be found on 1.0.x-dev branch.
So you need to run command: composer require appzcoder/crud-generator:1.0.x-dev

And I will soon release the stable version then you don't need to use dev version.

Cheers
