### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by cjke** [appzcoder/crud-generator#202]
A few enhancements - happy to do PR's but want to make sure it lines up to your vision first. 

## One

At the moment it feels very much like a one use tool (it is a generator, so makes sense) - you run the generator, it creates everything and thats that. In reality though, I frequently add, modify and otherwise change models, migrations, etc. 

It would be good if this tool could account for that - much like Django's admin feature. There are a core set of models (this would be somewhat similar to your .json definitions), and from that everything is generated. The difference being that you can make updates to those core definitions and re-run the command and everything will update. 

If you do that with crud-generator it:
 - Doesn't update the controller 
 - Doesn't update the model
 - Creates a new migration (so you end up with multiple migrations)
 - Updates the view

So already, there are 3 possible outcomes (a "no update", a "new" and a "replace"). I understand not updating, but if that is desired, it should be the same for all. 

Ideally though, running update (possibly with a --force) would re-generate everything. 

So based on this - using models, possibly with some form of annotations instead of the .json would facilitate this. That way a user can update their models (and act as the source of truth), and migrations, controllers, and views are generated. 

## Two

A lot of awkward functionality is introduced by trying to get the CrudCommand to call the subcommands (joining relationships on '#' then splitting them back out). I suggest that you seperate out a set of service classes - one for each each command. Eg. CrudControllerService. In turn both CrudCommand and CrudControllerCommand invoke CrudControllerService, instead of CrudCommand trying to communicate directly with CrudControllerCommand via strings in the command line. 

## Three 

And... this leads on to the third - relationships. It would be nice to start to introduce relationships (see attached image). Starting with belongsTo would be a good start - where instead of typing the id of the related model, a drop down would be used. 

I've tried to tackle this, but the passing relationship strings along the command line is becoming unweirdly (hence the request for the second feature above (services)). 

![image](https://user-images.githubusercontent.com/884065/33832474-6d1fbaca-ded0-11e7-9499-9378a5680b94.png)

## Four

Finally :) - How do you feel about using blade instead of the manual string replaces everywhere? For example: 
![image](https://user-images.githubusercontent.com/884065/33832907-ee3a0bc8-ded1-11e7-8b22-8d3289d53d4c.png)

The image is just really basic sample stuff - but it would really clean up the generators by not having to have str_replace everywhere.

**Comment by raulneis** [comment]
I think this will add a lot of value to the project. I'm really looking forward to contribute, so let me know if I can help.

Feature number one would be very useful and challenging to implement.

Feature number three is like a must, since every project needs relationships.

Features number two and four will bring order and clean up the code, so will be useful too.

**Comment by cjke** [comment]
Yeah for sure - agree with your points. 
I haven't heard back as yet - so I'm kind of doing a from scratch version to a specific project for a client, but will loop back to see if there is any interest from the owner

**Comment by kikoseijo** [comment]
@cjke you had any responses about the maintainer?

won't mind collaborating to build the select with relationships.

right now im trying to integrate with own package using this function:

https://gist.github.com/kikoseijo/b3ceef0d25801248bacc7615b62bf3ea

This is the package im using to build the Repository and interactions.

https://github.com/kikoseijo/klaravel

**Comment by cjke** [comment]
No I'm not sure. I've started to introduce my ideas into my own pacakge too. They were to drastic to commence without getting sign off from the maintainer first

**Comment by sohelamin** [comment]
@cjke Thanks for your great proposal and sorry for the late notice.
I liked your suggestions about the package especially the Django like CRUD further modification way.
But you may know implementing all those stuffs into this package so much challenging that's why I've no plan for yet. But definitely I will think about it very soon.

**Comment by stelgenhof** [comment]
For me the suggestions from @cjke are definitely valuable additions. 

Number one is extremely helpful especially in the early stages of your project when your model, controllers, etc change a lot. Also when you use custom stubs, and having the option to force an overwrite for example saves you time deleting the generated model, and controller.

**Comment by cjke** [comment]
@sohelamin That's cool, no worries. I might just spin up my own - ultimately it sounds like my suggested approach is too drastically different (this project is a generator at the end of the day). I just didn't want to go reinventing the wheel (its a bit too common in OSS world, which is why we end up with 10 libraries doing the same thing). 

Good luck with the project!

**Comment by sohelamin** [comment]
@cjke I think you got it wrongly, I always welcome PRs.

**Comment by cjke** [comment]
I understand you welcome PRs but my suggestions do sound like they are quite different from the direction you are heading
