### ISSUE TITLE
Bug in Usage part

### ISSUE THREAD

**Issue by ibrahimbadram** [appzcoder/crud-generator#208]
After passing the CRUD command  : php artisan crud:generate Posts --fields='title#string; content#text; category#select#options={"technology": "Technology", "tips": "Tips", "health": "Health"}' --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=html

I have the following error: Too many arguments expected arguments "command" "name".

what does mean and what I should do to fix this error?

**Comment by sohelamin** [comment]
I just ran your command
```
php artisan crud:generate Posts --fields='title#string; content#text; category#select#options={"technology": "Technology", "tips": "Tips", "health": "Health"}' --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=html
```
and everything is fine.

**Comment by YogeshMoreD** [comment]
![image](https://user-images.githubusercontent.com/24932160/35903372-df647c7c-0c04-11e8-96df-99008eb57ab4.png)
Same problem again !

**Comment by agadis** [comment]
Hello, 
That is single quotes problem. I used: 
php artisan crud:generate Posts --fields="title#string; content#text; category#select#options={"technology": "Technology", "tips": "Tips", "health": "Health"}" --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=html

and "too many arguments" error has gone.

**Comment by matiasmanoel** [comment]
the problem is simple, use " " in the place of ' ', because " " support more arguments

**Comment by mfrancaleal** [comment]
I am using "" and I have same problem. See the command:

php artisan crud:generate Fornecedores --fields_from_file="/resources/crudGenerator/fornecedorFields"
--view-path=admin --controller-namespace=Admin --route-group=admin form-helper=html

My file .json

{
    "fields": [
        {
            "name": "razao_social",
            "type": "string"
        },
        {
            "name": "cnpj",
            "type": "text"
        },
        {
            "name": "estado",
            "type": "select",
            "options": {
                "AC": "Acre",
                "AL": "Alagoas",
                "AP": "Amapá",
                "AM": "Amazonas",
                "BA": "Bahia",
                "CE": "Ceará",
                "DF": "Distrito Federal",
                "ES": "Espírito Santo",
                "GO": "Goiás",
                "MA": "Maranhão",
                "MT": "Mato Grosso",
                "MS": "Mato Grosso do Sul",
                "MG": "Minas Gerais",
                "PA": "Pará",
                "PB": "Paraíba",
                "PR": "Paraná",
                "PE": "Pernambuco",
                "PI": "Piauí",
                "RJ": "Rio de Janeiro",
                "RN": "Rio Grande do Norte",
                "RS": "Rio Grande do Sul",
                "RO": "Rondônia",
                "RR": "Roraima",
                "SC": "Santa Catarina",
                "SP": "São Paulo",
                "SE": "Sergipe",
                "TO": "Tocantins"
            }
        },
        {
            "name": "cidade",
            "type": "text"
        },
        {
            "name": "logradouro",
            "type": "select",
            "options": {
                "avenida": "Avenida",
                "alameda": "Alameda",
                "beco": "Beco",
                "rua": "Rua",
                "travessa": "Travessa",
                "viela": "Viela"
            }
        },
        {
            "name": "complemento",
            "type": "text"
        },
        {
            "name": "cep",
            "type": "text"
        },
        {
            "name": "tel1",
            "type": "text"
        },
        {
            "name": "tel2",
            "type": "text"
        },
        {
            "name": "email",
            "type": "text"
        },
        {
            "name": "responsavel",
            "type": "text"
        },
        {
            "name": "user_id",
            "type": "integer#unsigned"
        }
    ],
    "validations": [
        {
            "field": "responsavel",
            "rules": "required|max:15"
        },
        {
            "field": "razao_social",
            "rules": "required|max:15"
        },{
            "field": "email",
            "rules": "required|max:30"
        },{
            "field": "complemento",
            "rules": "required|max:30"
        }
    ]
}

**Comment by EudesSA** [comment]
conseguiram resolver esse problema ?
