### ISSUE TITLE
Gruping all cruds views in one folder

### ISSUE THREAD

**Issue by radiart** [appzcoder/crud-generator#21]
Hi can you add option for grouping all views in one folder eg. /admin or /panel ?

**Comment by sohelamin** [comment]
Hi @radiart,

Thanks for your idea.
I've added some new features recently.
You can set your view directory as bellow command:
php artisan crud:generate Person --fields="name:string, email:string, phone:integer, message:text" --view-path=admin

This feature you will found on 1.0.x-dev branch.
So you need to run command: composer require appzcoder/crud-generator:1.0.x-dev

And I will soon release the stable version then you don't need to use dev version.

Thanks
