### ISSUE TITLE
Usage of php artisan optimize in laravel >=5.6

### ISSUE THREAD

**Issue by Shifty-kek** [appzcoder/crud-generator#213]
**Problem**
https://laravel-news.com/laravel-5-6-removes-artisan-optimize
**Solution**
Simply wrap command call into  App::version() check like so:

`if (\App::VERSION() < '5.6') {`
   ` $this->callSilent('optimize');`
`}`

**Comment by sohelamin** [comment]
@Shifty-kek Thanks for the notice will update it on the next release.

**Comment by sohelamin** [comment]
Fixed at the new release
