### ISSUE TITLE
"File does not exist at path {$path}"

### ISSUE THREAD

**Issue by sinaxtis** [appzcoder/crud-generator#214]
I am starting to use it crud generator and when y I tried this
php artisan crud:generate Photo --fields_from_file="fields.json" --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=htm
Controller created successfully
Model created successfully.
Migration created successfully.

 Illuminate\Contracts\Filesystem\FileNotFoundException 
File does not exist at path C:\Users\sinaxtis\Desktop\phot\phot\vendor\appzcoder
\crud-generator\src\Commands/../stubs/views/htm/form-fields/form-field.blade.stub

C:\Users\sinaxtis\Desktop\phot\phot\vendor\laravel\framework\src\Illum
inate\Filesystem\Filesystem.php
  37:         if ($this->isFile($path)) {
  38:             return $lock ? $this->sharedGet($path) : file_get_contents($pa
th);
  39:         }
  40:
  41:    throw new FileNotFoundException("File does not exist at path
{$path}");
  42:     }
  43:
  44:     /**
  45:      * Get contents of a file with shared access.
  46:      *

  Exception trace:

  Illuminate\Filesystem\Filesystem::get("C:\Users\sinaxtis\De
sktop\phot\phot\vendor\appzcoder\crud-generator\src\Commands/../stubs/views/htm/
form-fields/form-field.blade.stub")
   C:\Users\sinaxtis\Desktop\phot\phot\vendor\laravel\framework\src\Illu
minate\Support\Facades\Facade.php

Illuminate\Support\Facades\Facade::__callStatic("get")

C:\Users\sinaxtis\Desktop\phot\phot\vendor\appzcoder\crud-generator\s
rc\Commands\CrudViewCommand.php

I am using Laravel 5.6 and PHP 7, please help.

**Comment by sohelamin** [comment]
@sinaxtis You used wrong form-helper
Run `php artisan crud:generate Photo --fields_from_file="fields.json" --view-path=admin --controller-namespace=Admin --route-group=admin --form-helper=html`
