### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [appzcoder/crud-generator#215]
I'm getting this error when I'm trying to generate api crud
![screenshot from 2018-02-27 13-31-49](https://user-images.githubusercontent.com/33511684/36718206-c3fdf3dc-1bc2-11e8-81ed-709687484e4d.png)
OS Ubuntu 17.10.1, PHP version 7.1.11 and Laravel 5.6.5

**Comment by sohelamin** [comment]
@AbdusamadTurdiev Thanks for the report will update it on the next release.
Meanwhile you can use from the develop branch.

**Comment by sohelamin** [comment]
Fixed at the new release
