### ISSUE TITLE
The "--fillable" option does not accept a value.

### ISSUE THREAD

**Issue by radiart** [appzcoder/crud-generator#22]
when I'm using: 

``php artisan crud:model Person --fillable="['name', 'email', 'message']"``

I see error:

``[RuntimeException]
  The "--fillable" option does not accept a value.``

**Comment by sohelamin** [comment]
Hi @radiart,

Thanks for let me know the bug.
I've just fix it and have planned to add it to the next release meanwhile you can use dev version.
composer require "appzcoder/crud-generator":"1.0.x-dev"

Thanks
Sohel Amin
