### ISSUE TITLE
Naming conventions plural singular

### ISSUE THREAD

**Issue by fishmad** [appzcoder/crud-generator#222]
I always thought views, routes and db tables are lowercase and plural.
models and controllers are supposed to be singular with uppercase first letters.

https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions

When using full crud, regardless of wether I write it as: fire, **F**ire, **f**ire**s** or **F**ire**s** the db table is always created as plural but the model,controller, views and routes change according to how I structure my text (plural, singular, lcwords, ucwords)

`php artisan crud:generate fire --fields='title#string; content#text'`

**_What actually gets auto generated:_**

**Model:** fire.php
**Controller** = fireController.php
**Route** = Route::resource('fire', 'fireController');
**Views** = /fire
**DB Table** = fires

`php artisan crud:generate fire --fields='title#string; content#text'`

**_What I anticipated would be generated:_**

**Model:** **F**ire.php
**Controller** = **F**ireController.php
**Route** = Route::resource('fire**s**', 'fireController');
**Views** = /fire**s**
**DB Table** = fires

`php artisan crud:generate Fires --fields='title#string; content#text'`

**_What I thought would occur but it doesnt:_**

**Model:** **F**ire.php
**Controller** = **F**ireController.php
**Route** = Route::resource('fire**s**', 'fireController');
**Views** = /fire**s**
**DB Table** = fires

Can the commands be coded to deal with any user-input error: plural, singular, lcwords, ucwords and so on, so regardless of me entering fire, **F**ire, **f**ire**s** or **F**ire**s** the system can automatically correct it as above or have you created it to be this way - free-text flexible?

At the end of the days it still works great, I might just be too anal.

**Comment by sohelamin** [comment]
Auto correction is chaos sometimes so I gave the control to the users.
