### ISSUE TITLE
The Blade "or" operator has been removed in laravel 5.7

### ISSUE THREAD

**Issue by bsh** [appzcoder/crud-generator#233]
The Blade "or" operator has been removed in favor of PHP's built-in ?? "null coalesce" operator, which has the same purpose and functionality:

// Laravel 5.6...
<input class="form-control" name="%%itemName%%" type="%%fieldType%%" id="%%itemName%%" value="{{ $%%crudNameSingular%%->%%itemName%% or ''}}" %%required%%>

// Laravel 5.7...
<input class="form-control" name="%%itemName%%" type="%%fieldType%%" id="%%itemName%%" value="{{ $%%crudNameSingular%%->%%itemName%% ?? ''}}" %%required%%>

**Comment by sohelamin** [comment]
Fixed now
