### ISSUE TITLE
Any plans to integrate the UI like the Admin project?

### ISSUE THREAD

**Issue by mnazmi23** [appzcoder/crud-generator#255]
As per title, this is the closest thing I want but I would like to have the UI option like in your admin panel project.

**Comment by alaminshakeel** [comment]
i guess this project was planned to integrate in any project and get facilitated by running command in terminal. i have been using this package since so long.

when i need to add the base feature of it under the hood i use this. and prefer to jump start with `Laravel-Admin`  @mnazmi23
