### ISSUE TITLE
Laravel 9 support 

### ISSUE THREAD

**Issue by fh32000** [appzcoder/crud-generator#266]
add support for laravel 9
 "appzcoder/crud-generator": "^3.2.2",
 php :8.0.2

**Comment by johnnydoe82** [comment]
Hi @fh32000 ,
I made a pull request to the maintainer (@sohelamin ), that should make this package compatible with Laravel 9. Hope it can be accepted and merged soon. In the meanwhile you could download my fork of the repo: https://github.com/johnnydoe82/crud-generator, and install it via the local copy, like described in https://stackoverflow.com/questions/29994088/composer-require-local-package#answer-39802804. Hope this helps for the moment.
