### ISSUE TITLE
not found option to set my own layout

### ISSUE THREAD

**Issue by lucky-saini** [appzcoder/crud-generator#27]
Hi,

Can you please tell me how can I give my required style to crud pages. So that I can save my time to set layout the pages. Because if I update in package files then these will remove then I run 'composer update' command.

It will very helpful if you provide me such option. 
Thanks

**Comment by sohelamin** [comment]
Hi @lucky-saini 

You can use your own layout for all cruds.
For this just put your layout file to /resources/views/layouts/master.blade.php
Once you have your own layout file exist previously then the package will not make new layout file.

Let me know if you still having issues.

Cheers.
