### ISSUE TITLE
Should --view-path="admin" Be used in Routes/Redirects/etc

### ISSUE THREAD

**Issue by vita10gy** [appzcoder/crud-generator#28]
To say I'm "very new to Laravel" would be an understatement, but we're looking to transition from a custom thing to something like laravel. One of the things I like about our custom approach is we can generate a full CRUD process from a given DB table. Hence why I'm interested in this project.

We like to have all these admin things in /admin/ (though might not be the end of the world to let that go) and I see you have --view-path="admin" as an option. Problem is it only seems to matter for the blades (which I realize is the views). 

However, if you do that, nothing seems to work until you get everything else working at /admin/widget which takes a change to the route file, any urls in the blades, and the redirects in the controller. 

Am I missing something obvious, or should all those other changes be implied by --view-path="admin" as well?

**Comment by sohelamin** [comment]
Hi @vita10gy,

 --view-path="admin" option will let you separate the view files.
This generator will allow you to separate the controller in different directory.

If you like to put your controller to separate directory and want to add prefix on route as well then 
You need to do it manually. 

Make the route as like

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('crud', function ()    {
        // Matches The "/admin/crud" URL
    });
});

Make your controller namespace as like
namespace App\Http\Controllers\Admin;

Put the controller file to the directory
app/Http/Controllers/Admin

Thanks

**Comment by vita10gy** [comment]
How possible would making some parameter to automate that be?

**Comment by sohelamin** [comment]
I will be added this feature soon.

**Comment by sohelamin** [comment]
Hi @vita10gy  check this features on new version.
And let me know your feedback.
