### ISSUE TITLE
"composer require" this package doesn't work

### ISSUE THREAD

**Issue by LeonardoCaitano** [appzcoder/crud-generator#29]
composer require abmti/laravel-scaffold-generate

                                                                                
  [InvalidArgumentException]                                                    
  Could not find package abmti/laravel-scaffold-generate at any version for your minimum-stability (stable). Check th
  e package spelling or your minimum-stability                                  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

**Comment by LeonardoCaitano** [comment]
Solved:

composer require "appzcoder/crud-generator":"1.0.3"

**Comment by sohelamin** [comment]
Hi @LeonardoCaitano ,

I think your used package is not stable one and it is forked from my package.
You can install it by composer require appzcoder/crud-generator

Feel free to let me know if you getting still any issue.

Thanks
