### ISSUE TITLE
--namespace not available

### ISSUE THREAD

**Issue by Mythos** [appzcoder/crud-generator#34]
I'm using v1.0.4 and according to the 1.0 branch there's an option for --namespace, but the CLI says this option is not available.

**Comment by remailednet** [comment]
I hadn't tried using the namespace option myself until you mentioned it.

It seems to work just fine when I test it out.

```bash
$ php artisan crud:generate Test --fields="name:string" --namespace="test\namespace"
Controller created successfully.
Model created successfully.
Migration created successfully.
View created successfully.
Crud/Resource route added to /Users/james/Desktop/projects/laravel-boilerplate/app/Http/routes.php
```

Paste the command line that you are running?

**Comment by sohelamin** [comment]
Hi,
You can do that for now using "1.0.x-dev" version.
I will release the next stable release soon.
Cheers

**Comment by Mythos** [comment]
@remailednet I'm using following command:

```
php artisan crud:generate Task --fields="name:string, complete:boolean, due:datetime" --route=yes --pk=id --view-path="admin" --namespace=Admin
```

But I'll try the 1.0.x-dev version as @sohelamin said tonight.

**Comment by sohelamin** [comment]
Just released the stable version with namespace feature
