### ISSUE TITLE
Route groups

### ISSUE THREAD

**Issue by Mythos** [appzcoder/crud-generator#35]
It would be awesome if we could add a route group for our CRUD.

For example:

php artisan crud:generate Task --viewpath="admin" --namespace="Admin" --routegroup="admin"

Expected output would be that all routes are "admin/task" instead of "task". (Just for laziness)

**Comment by sohelamin** [comment]
Hi,
You can do that for now using "1.0.x-dev" version.
I will release the next stable release soon.
Cheers

**Comment by Mythos** [comment]
How can I do that? Documentation doesn't say anything about it.

**Comment by sohelamin** [comment]
Oh sorry that was for namespace I will add the route group soon.

**Comment by sohelamin** [comment]
Added the route group option
