### ISSUE TITLE
Customize templates

### ISSUE THREAD

**Issue by Mythos** [appzcoder/crud-generator#36]
As I requested some time ago on Laracasts, it would be nice if "php artisan vendor:publish" would publish the view/model/controller/etc. templates for further customization.

**Comment by geshan** [comment]
+1

**Comment by sohelamin** [comment]
Hi guys,

I've added custom/user defined template support.
Please check this out and let me know your feedback.
It can be found on dev version appzcoder/crud-generator:1.0.x-dev

**Comment by sohelamin** [comment]
Just released stable one 1.0.6

**Comment by Mythos** [comment]
Awesome. :+1:
