### ISSUE TITLE
Boolean radio buttons

### ISSUE THREAD

**Issue by Mythos** [appzcoder/crud-generator#37]
The generated boolean radio buttons look a bit weird, especially the second one.
Shouldn't booleans be handled as checkboxes? (just personal preference)

![radiobuttons](https://cloud.githubusercontent.com/assets/416568/11512257/86a1753e-986d-11e5-8946-dbaf9c0bcecd.JPG)

**Comment by sohelamin** [comment]
@Mythos please check now it might be working.

**Comment by Mythos** [comment]
It's fine now, thanks.
