### ISSUE TITLE
Adding new columns to an existing crud

### ISSUE THREAD

**Issue by ekeloglu** [appzcoder/crud-generator#41]
Hello,

Let's say we have a users table which has already created by crud:generate function and it has colums like below,

username | password | age

now i want to add another colums to this table which is "city" and table will be like below.

username | password | age | city

Is there a way to automatically add this column to all my views without changing my own changes in view files?

thank you.

**Comment by sohelamin** [comment]
No there is no option to do that for now. You should have to manually do that.
