### ISSUE TITLE
Customize %%formFieldsHtml%%

### ISSUE THREAD

**Issue by decalages** [appzcoder/crud-generator#44]
Hi,
Nice script, thanks a lot.
It would be nice to be able to customize the %%formFieldsHtml%% part as well

**Comment by garlian** [comment]
+1 for this!

**Comment by sohelamin** [comment]
Will add this later :)

**Comment by MaMouT514** [comment]
+1 for this too!

**Comment by sloan58** [comment]
Great package and a +1 for customizing %%formFieldsHtml%%

**Comment by ChangePlaces** [comment]
has this been implemented? I may as well take this on :)

**Comment by sohelamin** [comment]
No I didn't implement yet. 
You can proceed and many many thanks for your effort :)

**Comment by ebisbe** [comment]
@decalages @ChangePlaces 
What do you mean with customize this? You can override it with a CustomViewCommand that extends ViewCommand. Create your own views and pass your custom variables. That's why I made this change.  
You can check this gist for a example https://gist.github.com/ebisbe/6e2973708e07be64cc0e14c4dbc72e11

**Comment by bsadnu** [comment]
@ebisbe is right!
The simplest way is to override vendor commands. Just create command inside /app/Console/Commands
Here`s my example for StartUI admin template https://gist.github.com/bsadnu/b9ae489fb396bebf0ddc27b95d94153c

Don`t forget to put command to /app/Console/Kernel.php. Like this:
https://gist.github.com/bsadnu/e47e970336a8dd84629932b79476f572

Enjoy!

BTW. If someone dislike capital-first-letter filenames in /resources/lang you may also create custom command:
https://gist.github.com/bsadnu/65a09e2e94a0282260e7e3aac4b6e2cd
https://gist.github.com/bsadnu/e47e970336a8dd84629932b79476f572

**Comment by johnnydoe82** [comment]
Agree: great package @sohelamin 
Thanks @ebisbe and @bsadnu for showing how to customize form fields.

But I think it would even be better, if there where templates published into `"views/crud-generator/form-fields`" by running 
`php artisan vendor:publish --provider="Appzcoder\CrudGenerator\CrudGeneratorServiceProvider"`
There they could be "flat" blade files and would be more intuitive to edit (at least I think so). I know in "vendor/appzcoder/crud-generator/src/stubs" I can edit package assets (stub-files). But so far I don't know how to make %%formFieldsHtml%% in `"resources/crud-generator/form.blade.stub"` render fields from `"resources/crud-generator/form-fields"` by creating a new CRUD. Can anybody help me on this? :)

**Comment by sohelamin** [comment]
Hello Guys,

Recently @johnnydoe82 made awesome changes on ```%%formFieldsHtml%%``` section at c8dca17
Please have a look into this when you get some time and share your ideas.
