### ISSUE TITLE
Create own generated files

### ISSUE THREAD

**Issue by bekerov** [appzcoder/crud-generator#45]
Hello. Thanks for lib. I need generate in laravel 5 rest api routes, models and controllers without views and with my predefined code. IS it possible ?

**Comment by sohelamin** [comment]
Hi @bekerov  

Thanks dude for appreciate this.

For your purpose, you need to create model and controller separately here you go
https://github.com/appzcoder/crud-generator#other-commands-optional

**Comment by bekerov** [comment]
I can't publish `Nothing to publish for tag [].`
After clear cache same problem.

**Comment by sohelamin** [comment]
@bekerov 
Did you solve this?
If not then you can remove the "CrudGeneratorServiceProvider" service provider then run **composer update** then again add the service provider and run "CrudGeneratorServiceProvider""

**Comment by bekerov** [comment]
im try this. thanks
