### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by SaintGiff** [appzcoder/crud-generator#46]
I'm new to laravel so this may be an error on my end, however I am encountering the following issues.

When generating controllers with 

php artisan crud:generate Posts --route=yes --view-path="admin" --namespace=Admin --route-group=admin
 
I get the controller and model in the proper namespace, and the route is correct in routes.php.  However, the controller class is empty.  None of the methods are generated.  And no views are generated.

When I try to generate just a controller, say, if I wanted a separate UsersController within Admin, I am unable to use --route or --namespace as option.  This essentially means that I am unable to create the controller within Admin.

Any attempt to generate views for any controller results in a Symfony undefined offset: 1 error.

**Comment by sohelamin** [comment]
Hi @SaintGiff 

Maybe you forgot to include the fields.
You must need to define fields as well for this operation.
eg:
```
php artisan crud:generate Posts --fields="title:string:required, body:text:required" --route=yes --pk=id --view-path="admin" --namespace=Admin --route-group=admin
```
