### ISSUE TITLE
Crud Issue

### ISSUE THREAD

**Issue by adilsaeed31** [appzcoder/crud-generator#49]
HI,

I need some information, your crud generator is really awesome, well let me know i don't to generate the migration, i need only controller, model and views only, also route. but when i generate crud through your command, then in model my table name is automatically called with factories, instead of factory. so that is issue number 1.

2nd most important thing is when you write only (php artisan crud:generate TableName) and press enter it only create model/controller and route. why not create view, it should create view based on table columns, if table columns is already exist. so this is my suggestion please add this feature.

3rd thing after giving complete columns through command then your view only create four table heading in listing view plus migration which i don't need if i have already migration class exist.

4th thing what about foreign keys if we want dropdown as select tag then in your view you need to pull data from database table and display as option in select tag, 
for example:
I have country field like pakistan, bangladesh, and their values are 1, 2 so i need them while create. 

Hope you understand.

Please let me know.

Best Regards
Muhammad Adil

**Comment by sohelamin** [comment]
Thanks @adilsaeed31 for your suggestion and nice explanation.
I will do some changes near future but everything will be not possible to make cause I've to do others works.
Any way, PR are always acceptable.

Thanks again :)

**Comment by adilsaeed31** [comment]
Thanks for your reply, can i contribute to complete this.

**Comment by sohelamin** [comment]
Sure.

**Comment by sohelamin** [comment]
@adilsaeed31 you can check now I've already fixed some issues.
