### ISSUE TITLE
Routes option failing

### ISSUE THREAD

**Issue by azooziidev** [appzcoder/crud-generator#53]
`php artisan crud:controller TemplateController --crud-name=templates --model-name=Template --route-group=admin --routes=yes --view-path="admin"`

[RuntimeException]                     
  The "--routes" option does not exist. 

Also, no update on routes.php. I get this for both the crud:view and crud:controller commands. 

Any ideas much appreciated, this is an awesome tool otherwise.

**Comment by sohelamin** [comment]
Actually routes option is only for the crud **crud:generate**
If you like to add individual controller then you need to add route yourself to the routes file.

**Comment by azooziidev** [comment]
Got it. It threw me off with the —route-group options documented in the
crud:controller & crud:model examples, as I figured that would create the
route, but I now realize that data is needed to correctly setup the files,
wether or not the routes themselves are configured. It might make things a
tad more clear if you indicated in the docs that the —routes option was
only available to crud:generate.

Thank you very much for the response and for this project.

- Mark
