### ISSUE TITLE
CRUD from migration

### ISSUE THREAD

**Issue by twelvester** [appzcoder/crud-generator#57]
Is it possible to generate after i have created a migration table?

**Comment by sohelamin** [comment]
If you have already migration then you can generate other thing separately.
Check this https://github.com/appzcoder/crud-generator#other-commands-optional

**Comment by twelvester** [comment]
@sohelamin i see. But then i have to repeatedly type the fields for each of the commands and how about if i have made a change in the migration file?

**Comment by sohelamin** [comment]
Once you have created the crud thing or the individual then it will not effect on another if you made changes.
Thats why you need to make carefully everything with one line crud command then if you need any changes then you should manually do that.
