### ISSUE TITLE
In case of Class 'Form' not found error, just add illuminate/html package

### ISSUE THREAD

**Issue by preshetin** [appzcoder/crud-generator#6]
Nice package, thanks! 
Though, when implementing on fresh Laravel 5 app, it throws Class 'Form' not found error.

In case someone is confused, you need just to add illuminate/html package. Here are more details: http://laravel.io/forum/09-20-2014-html-form-class-not-found-in-laravel-5

**Comment by sohelamin** [comment]
Thanks @preshetin for sharing your thought.

Actually I leave it without illuminate/html package for user.
I thought users will configure it themselves.

If you want it to be there then I can add the package on composer require section or I can make a note on the repository's guides.

**Comment by preshetin** [comment]
@sohelamin well yes, actually I did not have any problems to add that package. So I think there is no extra need to require it in package. 

So, just wanted to give you respect :)

**Comment by appzcoder** [comment]
Hi @preshetin,

I've included "illuminate/html" package in my package also minimize the instruction.
So I think it will save the installation time.
Also I changed the UI (using bootswatch)
Please have a look and let me know about your thought. https://github.com/appzcoder/crud-generator

Thanks
Sohel Amin

**Comment by preshetin** [comment]
Ok, I have checked on fresh Laravel 5 app and confirm that the error disappeared. Now the process is smoother. 

So I think the issue may be closed.
