### ISSUE TITLE
Pass all variables to view stub files

### ISSUE THREAD

**Issue by azooziidev** [appzcoder/crud-generator#64]
I'm changing around the stub files for a different layout, and it would be very useful to have all the computed variables passed (i.e. replaced) in all of the different view stub files. For example, I'd like to use **%%crudNameCap%%** in the create.blade.stub & show.blade.stub files. Would you consider this in a future release?

Thanks in advance...

**Comment by sohelamin** [comment]
Check the new release for this option.

**Comment by azooziidev** [comment]
Awesome. Thanks!

- Mark Tyson
