### ISSUE TITLE
 [ErrorException] Undefined index: timestamp

### ISSUE THREAD

**Issue by icanfly777** [appzcoder/crud-generator#69]
hello,I use Crud command:

php artisan crud:generate Posts --fields="title:string:required,content:text:required,pubished_at:timestamp" --route=yes --pk=id --view-path="admin" --namespace=Admin --route-group=admin

But there were following errors:

Controller created successfully.
Model created successfully.
Migration created successfully.

  [ErrorException]
  Undefined index: timestamp

could you tell me how to solve, thank you！

**Comment by sohelamin** [comment]
Hi @icanfly777 

This issue is already fixed on "appzcoder/crud-generator: 1.0.x-dev"
I will add this on the next stable release soon.
