### ISSUE TITLE
Is this generator different from laracast generator?

### ISSUE THREAD

**Issue by jorgeas80** [appzcoder/crud-generator#70]
Hi,

Not sure if this is the right place to ask, but I couldn't find a better alternative. 

I'm a Laravel newbie, and found these 2 similar tools:

https://github.com/laracasts/Laravel-5-Generators-Extended
https://github.com/appzcoder/crud-generator

Are they different? Complementary? 

Many thanks in advance, and sorry if my question is innappropriate.

**Comment by sohelamin** [comment]
Hi @jorgeas80 

Actually it generates crud stuff like controller, model, migration, views within a single line command for a complete CRUD operation.
And you can also generate the individual stuff like laracasts generator.
Please read the docs for details https://github.com/appzcoder/crud-generator/blob/1.0/README.md

**Comment by jorgeas80** [comment]
Yes, I read it, but I didn't know if this is an alternative to extended generators. Looks like that. Actually, creates more stuff than them. That's cool. Thanks!
