### ISSUE TITLE
Can only create 3 column header on view

### ISSUE THREAD

**Issue by praditha** [appzcoder/crud-generator#71]
Hi,
I found this code in CrudViewCommand.php at line 135.

            ...
            foreach ($formFields as $key => $value) {
                        // Why this loop is limited by 3
                        if ($i == 3) {
                            break;
                        }

                        $field = $value['name'];
                        $label = ucwords(str_replace('_', ' ', $field));
                        $formHeadingHtml .= '<th>' . $label . '</th>';
            ...
            }

What is exactly the limitation until 3 for..? 
I think that should not be limited.

Thanks.

**Comment by sohelamin** [comment]
The limitation is for table field.
Suppose you want to generate a crud which will have more much fields eg: 10+
Then it will not let to generate table column for all fields.

**Comment by praditha** [comment]
Hmm, previously I tried to make only 4 fields, but it's only show 3 fields.
I think the column number is based on user requirement. Can you make the $defaultColumsToShow to be parameter, so we can set it based on our requirement..?

**Comment by sohelamin** [comment]
Okay I will set it on config file on the next release.

**Comment by sohelamin** [comment]
Check the new release for this option.
