### ISSUE TITLE
No commands found in the "crud" namespace

### ISSUE THREAD

**Issue by Ravenna** [appzcoder/crud-generator#72]
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "crud" namespace.  

When I run the generator.  I ran the composer require and update, and updated my app.config file with the right providers and aliases.  

I also ran php artisan vendor:publish

Any ideas

**Comment by sohelamin** [comment]
Can you share your command which one you're trying?
Also you could be sure if the generator's commands register or not via
```
php artisan
```

**Comment by Ravenna** [comment]
My apologies, should have been more clear: when running: 
php artisan crud:generate Buildings --fields="name:string:required, user_id:integer" --route=yes --pl=id --view-path="admin" --namespace=Admin --route-group=admin

I get that error.  Checking "php artisan" the commands are not listed.  I am using Laravel 5.2

**Comment by sohelamin** [comment]
I'm sure you have configuration problem.
Please try with new installation of laravel and follow the instructions carefully.

**Comment by bryanwokich** [comment]
I had this same error.  Double-checking config/app.php I was missing
            Appzcoder\CrudGenerator\CrudGeneratorServiceProvider::class,

**Comment by jashimcse2015** [comment]
when i run this commend php artisan crud:generate Posts --fields="title#string; content#text; category#select#options=technology,tips,health" --view-path=admin --controller-namespace=Admin --route-group=admin
composer show : There are no commands defined in the "crud" namespace.

**Comment by jashimcse2015** [comment]
i am using laravel 5.4

**Comment by sohelamin** [comment]
Follow the installation instructions properly

**Comment by yaimran21** [comment]
add the provider in app/Providers/AppServiceProvider.php.


public function register()
{
    if ($this->app->environment() == 'local') {
        $this->app->register('Appzcoder\CrudGenerator\CrudGeneratorServiceProvider');
    }
}



I think you should solve this problem

**Comment by israr-roohware** [comment]
@yaimran21 thanks. You solved my problem.
