### ISSUE TITLE
assertion "newSize >= 0" failed: file "main.cc", line 232, function: std::string convertPosixPathToWin(const string&) Aborted (core dumped)

### ISSUE THREAD

**Issue by LeifErickson** [appzcoder/crud-generator#73]
After running this: php artisan crud:generate Members --fields="membershiptype:string:required, firstname:string:required, lastname:string:required, middlename:string:required, emailaddress:string, cellphonenumber:string, residenceadd:string, residencetelephoneno:string, residencefaxno:string, officeadd:string" --route=yes --pk=id --view-path="admin" --namespace=Admin --route-group=admin

It returns me that error

**Comment by sohelamin** [comment]
Which platform are you using now?
Seems you are using emulator and the error is coming from there.
I totally sure it is not wrong with the generator.

**Comment by LeifErickson** [comment]
Im not using an emulator. Im on windows. It works on the other command but when i executed that, the error pops out

**Comment by sohelamin** [comment]
Actually I've never heard any issue like that regarding on windows machine with this package.
Please try with different machine or different platform.
