### ISSUE TITLE
Not all names work well with functions str_singular / str_plural 

### ISSUE THREAD

**Issue by eduardoarandah** [appzcoder/crud-generator#79]
for example in spanish plurals might end with "s" "es" "as"
to make it worse, some singulars also end with "s" like "mes" (month in spanish)

what if we add the option for the generators?

```
class CrudCommand extends Command
{
...
        {--singular= : singular for the crud name}
        ';
```

**Comment by sohelamin** [comment]
Great idea (y)
We can make it optional **option** eg: if someone fill it then generator will assume from this option otherwise will try to make singular from the crud name(plural).

**Comment by eduardoarandah** [comment]
It will also help people that always use singular forms (like me)

El martes, 10 de mayo de 2016, Sohel Amin <notifications@github.com>
escribió:

> Great idea (y)
> We can make it optional *option* eg: if someone fill it then generator
> will assume from this option otherwise will try to make singular from the
> crud name(plural).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/appzcoder/crud-generator/issues/79#issuecomment-218150266>
>


-- 
Enviado desde mi móvil

**Comment by sohelamin** [comment]
Yeah you can make a PR for this option.
