### ISSUE TITLE
Cannot Create View

### ISSUE THREAD

**Issue by hafizhassan** [appzcoder/crud-generator#81]
hello, im using this crud. but when i try to generate. it show an error.
![screen shot 2016-05-11 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/4852934/15172605/8c1b7b72-1789-11e6-9b89-42422834ef7d.png)

**Comment by sohelamin** [comment]
Please try with the new version.

**Comment by hafizhassan** [comment]
fixed. thanks..
