### ISSUE TITLE
Adding data with crud.

### ISSUE THREAD

**Issue by hafizhassan** [appzcoder/crud-generator#83]
When i create new data, it created twice.
am i missing something?

**Comment by hafizhassan** [comment]
![screen shot 2016-05-12 at 3 11 50 am](https://cloud.githubusercontent.com/assets/4852934/15193228/582cb4fa-17ef-11e6-955c-c70b0b1f1703.png)

it like post 2 form

**Comment by hafizhassan** [comment]
![screen shot 2016-05-12 at 3 13 21 am](https://cloud.githubusercontent.com/assets/4852934/15193268/894a8170-17ef-11e6-8b83-84c64c51a8ac.png)
this is my form

**Comment by hafizhassan** [comment]
![screen shot 2016-05-12 at 3 14 22 am](https://cloud.githubusercontent.com/assets/4852934/15193300/aa25efe2-17ef-11e6-8efd-495aca1d338e.png)
controller.

**Comment by sohelamin** [comment]
Hi @hafizhassan 
Maybe you're doing something wrong here its working as expected.
Please try with the latest version or try again.
