### ISSUE TITLE
Broken views and controllers when using any caps in the crud name.

### ISSUE THREAD

**Issue by Scott-Stephen** [appzcoder/crud-generator#87]
You snake case the views ($viewName) and ($this->routeName) in crudCommand.php but do not use it in the stubs there for if you create a CRUD with a name like ProfilePicture it converts it to profile-picture for the view locations  but they are referenced using crudName (profilepicture) in the views there for breaking the created CRUD.

I hope this makes sence to you, just try creating any CRUD with a name madeup of 2 words using capital letters for each word as in the given example above.

**Comment by butoibogdan** [comment]
I have the same problems :) please fix it

**Comment by butoibogdan** [comment]
can you put the language optional ?

**Comment by sohelamin** [comment]
Okay I will make the fixes and will on the next release.
Thank for letting me know that
