### ISSUE TITLE
Enum Field Type

### ISSUE THREAD

**Issue by kemal-atila** [appzcoder/crud-generator#89]
Hi Sohel,

As the first I liked your Scaffold App.
Will crud-generator supports 'Enum' field type?

**Comment by sohelamin** [comment]
Not yet. I will add this support soon.

**Comment by sohelamin** [comment]
Implemented at cfdfc0e
Will add on next release with docs

**Comment by kemal-atila** [comment]
It will be useful feature. Thank you for interested in.
