### ISSUE TITLE
Too many arguments.

### ISSUE THREAD

**Issue by louiscoetzee** [appzcoder/crud-generator#93]
Hi there, trying to generate CRUD, but I get the following error (please see below):

One of my colleagues tried it and it works 100% on his side. Any help will be much appreciated.
Thank you for the great contribution.

`php artisan crud:generate Clients --fields=“organization_name#string#required, registered_name#string#required, organization_type_id#integer#required, registration_number#integer#required, vat_number#string, vendor_number#string, switchboard_number#string#required, fax_number#string, company_email_address#string#required, physical_address#text, postal_address#text#required, industry_id#integer, country_id#integer#required, province_id#integer#required, city_id#integer#required, suburb#string#required, notes#text” --route=yes --view-path=“backend” --route-group=“backend”`

Error:
`←[37;41m                                                          ←[39;49m
←[37;41m  [Symfony\Component\Console\Exception\RuntimeException]  ←[39;49m
←[37;41m  Too many arguments.                      ←[39;49m
←[37;41m                                                          ←[39;49m`

**Comment by sohelamin** [comment]
Hi @louiscoetzee 

Glad to hear that you liked it :)
I've just run your given command everything seems okay to me.
Please try again with the below command.

```
php artisan crud:generate Clients --fields="organization_name#string#required, registered_name#string#required, organization_type_id#integer#required, registration_number#integer#required, vat_number#string, vendor_number#string, switchboard_number#string#required, fax_number#string, company_email_address#string#required, physical_address#text, postal_address#text#required, industry_id#integer, country_id#integer#required, province_id#integer#required, city_id#integer#required, suburb#string#required, notes#text" --route=yes --view-path="backend" --route-group="backend"
```

Make sure you use double quotes in proper format and full command in single line.

**Comment by louiscoetzee** [comment]
Hi @sohelamin thank you for your prompt reply, that was the issue.
