### ISSUE TITLE
Cannot create views

### ISSUE THREAD

**Issue by ericmuga** [appzcoder/crud-generator#94]
I've seen this issue closed on issue #81 but the x-dev and dev-master still dont work. I get the same error as in #81.

**Comment by sohelamin** [comment]
Did you try the stable version 1.0.9 ? 
```composer require appzcoder/crud-generator```
I've just checked and everything seems okay.

**Comment by ericmuga** [comment]
hello sohel, actually the issue is if you run the command inside vim editor. I realized if I run it in plain terminal it works, may be some characters like # are unique to various vim configurations. Thanks anyway.
