### ISSUE TITLE
CamelCase Issue

### ISSUE THREAD

**Issue by DC-Adams** [appzcoder/crud-generator#95]
Hi,

**Awesome plugin for Laravel**, I am new to Laravel and have found this to be quite a useful plugin.

I have picked up on one issue while using it. 

I get "**-**"(dashes) between words when generating a CRUD where my view name has **more than one word** and I type it in **CamelCase**.

So for example: I generate a CRUD for "**AwesomeGenerator**" and my view folder comes through as "**awesome-generator**", then in my views all the variables, titles and url's containing the view name get displayed as "**awesome-generator**" with dashes between them as well. 

However when I go to my Controller -> "**AwesomeGeneratorController**". Where it specifies which views are returned, they are then displayed as one line without dashes e.g: "**return view(awesomegenerator.index)**".

This really is an awesome plugin but I think if we could get a fix for this it would be so much better and make developing awesome things even faster.

Thank you so much, your assistance is highly appreciated.

**Comment by sohelamin** [comment]
This issue is solved at dev version will release soon on the stable version.

**Comment by DC-Adams** [comment]
Thank you so much **tirjok** and **sohelamin**. I have tested this and it seems to be working perfectly now. We can now continue creating amazing things even faster now. **Great job guys**.
