### ISSUE TITLE
Docs: qualify your provider

### ISSUE THREAD

**Issue by jonrmitchell** [appzcoder/crud-generator#98]
Currently your documentation (Installation, step 5) encourages use of `php artisan vendor:publish` to publish your assets. This command publishes ALL assets from ALL plugins and can have unintended side effects. 
You might consider qualifying the vendor:publish command to include your specific provider:

```
php artisan vendor:publish --provider="Appzcoder\CrudGenerator\CrudGeneratorServiceProvider"
```

**Comment by jonrmitchell** [comment]
See also https://laravel.com/docs/master/packages#publishing-file-groups

**Comment by sohelamin** [comment]
Okay just added the provider name :)
