### ISSUE TITLE
forms.blade.php ?

### ISSUE THREAD

**Issue by MaMouT514** [appzcoder/crud-generator#99]
Maybe create a "forms.blade.php" and include it in "create.blade.php" and "edit.blade.php" ?
Most of the time it's the same content...
And thanks for this helpfull module!

**Comment by sohelamin** [comment]
I did not put form on a common view because of flexibility.

**Comment by ChangePlaces** [comment]
This is a good point, and one which would increase flexibility and templating - let's reopen this!
